### ISSUE TITLE
stop working on version DL 0.2.3

### ISSUE THREAD

**Issue by cyberbol** [sean1832/pinterest-dl-gui#5]
TypeError: PinterestDL.with_api() got an unexpected keyword argument 'ensure_alt'
Traceback:
File "D:\AI\pinterest-dl-gui\pinterest-dl-gui\venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "D:\AI\pinterest-dl-gui\pinterest-dl-gui\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
File "D:\AI\pinterest-dl-gui\pinterest-dl-gui\gui.py", line 339, in <module>
    main()
File "D:\AI\pinterest-dl-gui\pinterest-dl-gui\gui.py", line 302, in main
    scrape_images(
File "D:\AI\pinterest-dl-gui\pinterest-dl-gui\gui.py", line 226, in scrape_images
    api_instance = PinterestDL.with_api(
                   ^^^^^^^^^^^^^^^^^^^^^

**Comment by sean1832** [comment]
I'll close this issue. 
Should you have any problem, please feel free reopen this or submit another issue.
